Repository karpetrosyan/hishel, pull requests merged in 2023-11, with the labels that each got.

#104 Gracefully fail when freshness cannot be calculated
  CHANGELOG.md
  hishel/_controller.py
  tests/test_controller.py
Labels: enhancement, RFC

#106 Use ruff for formatting
  hishel/_async/_mock.py
  hishel/_async/_pool.py
  hishel/_async/_storages.py
  hishel/_async/_transports.py
  hishel/_controller.py
  hishel/_files.py
  hishel/_headers.py
  hishel/_serializers.py
  hishel/_sync/_mock.py
  hishel/_sync/_pool.py
  hishel/_sync/_storages.py
  hishel/_sync/_transports.py
  hishel/_utils.py
  scripts/check
  scripts/lint
  tests/_async/test_client.py
  tests/_async/test_pool.py
  tests/_async/test_storages.py
  tests/_async/test_transport.py
  tests/_sync/test_client.py
  tests/_sync/test_pool.py
  tests/_sync/test_storages.py
  tests/_sync/test_transport.py
  tests/test_controller.py
  tests/test_headers.py
  tests/test_serializers.py
  tests/test_utils.py
Labels: dependencies

#110 Documenting Heuristically Cacheable Status Codes
  docs/advanced/controllers.md
  hishel/_controller.py
Labels: documentation, enhancement

#109 Add cache_disabled extension
  CHANGELOG.md
  docs/advanced/extensions.md
  docs/userguide.md
  hishel/_async/_pool.py
  hishel/_async/_transports.py
  hishel/_sync/_pool.py
  hishel/_sync/_transports.py
  mkdocs.yml
  tests/_async/test_pool.py
  tests/_async/test_transport.py
  tests/_sync/test_pool.py
  tests/_sync/test_transport.py
Labels: enhancement

#117 Add force_cache extension
  CHANGELOG.md
  docs/advanced/extensions.md
  hishel/_controller.py
  tests/test_controller.py
Labels: enhancement

#119 Fix ttl for the SQLiteStorage
  CHANGELOG.md
  hishel/_async/_storages.py
  hishel/_sync/_storages.py
  tests/_async/test_storages.py
  tests/_sync/test_storages.py
Labels: bug

#107 Support float ttl
  CHANGELOG.md
  hishel/_async/_storages.py
  hishel/_sync/_storages.py
  hishel/_utils.py
  tests/_async/test_storages.py
  tests/_sync/test_storages.py
  tests/test_utils.py
Labels: enhancement
